export const THEME_CATEGORIES = [
  "风光",
  "人像",
  "街拍",
  "静物",
  "建筑",
  "纪实",
  "微距",
  "夜景",
  "黑白",
  "其他",
];

export const LOCATION_MAPPING: Record<string, string[]> = {
  "北京": ["北京", "beijing"],
  "上海": ["上海", "shanghai"],
  "广州": ["广州", "guangzhou"],
  "深圳": ["深圳", "shenzhen"],
  "杭州": ["杭州", "hangzhou"],
  "成都": ["成都", "chengdu"],
  "重庆": ["重庆", "chongqing"],
  "西安": ["西安", "xian"],
  "南京": ["南京", "nanjing"],
  "武汉": ["武汉", "wuhan"],
  "苏州": ["苏州", "suzhou"],
  "厦门": ["厦门", "xiamen"],
  "青岛": ["青岛", "qingdao"],
  "大连": ["大连", "dalian"],
  "三亚": ["三亚", "sanya"],
  "丽江": ["丽江", "lijiang"],
  "大理": ["大理", "dali"],
  "西藏": ["西藏", "拉萨", "lhasa", "tibet"],
  "新疆": ["新疆", "乌鲁木齐", "xinjiang"],
  "云南": ["云南", "yunnan"],
  "四川": ["四川", "sichuan"],
  "江南": ["江南", "周庄", "乌镇", "西塘"],
};
